#!/usr/bin/env ruby
# Copy from https://github.com/hsbt/hsbt/blob/master/libexec/dev-source-update

require 'bundler/inline'

gemfile true do
  source 'https://rubygems.org'
  gem 'parallel', require: true
end


Dir.chdir(`ghq root`.chomp) do
  Parallel.map(`ghq list`.split.shuffle) do |dir|
    next unless File.directory?(dir + '/.git')

    puts dir

    Dir.chdir(dir) do
      system('git stash')
      system("git remote show origin | grep 'HEAD branch' | awk '{print $NF}' | xargs git switch")
      system("git pull --rebase --prune")
      system('git submodule update --init --recursive')
      system('git gc --prune')
    end
  end
end

